---
- hosts: elasticsearch_cluster
  gather_facts: no
  vars:
    - base_directory: /data/app
    - es_start_user: elasticsearch
    - es_cluster_name: test-cluster
    - es_discovery_seed_hosts_hosts: '"192.168.156.123","192.168.156.124","192.168.156.125"'
    - es_cluster_initial_master_nodes: '"192.168.156.123","192.168.156.124","192.168.156.125"'
    - es_bootstrap_memory_lock: true
    - es_cluster_super_user: logadmin
    - es_cluster_super_user_password: password
    - es_cluster_memory_small: 1
    - es_cluster_memory_max: 1
    - es_version: 7.17.3
    - os_arch: x86_64

  roles:
   - role: elasticsearch-cluster